# Generated by Django 4.0.4 on 2022-04-18 15:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Nome')),
                ('crm', models.IntegerField(unique=True, verbose_name='CRM')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['nome', 'crm'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('data_agendamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de agendamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='Medicar.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['dia', 'horario'],
                'unique_together': {('dia', 'horario')},
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('horarios', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='Horários'), size=None)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='Medicar.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['dia', 'horarios'],
                'unique_together': {('medico', 'dia')},
            },
        ),
    ]
